name: validate terraform
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - modules/**/*
jobs:
  directories:
    name: "List directories"
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.setdirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v4
      - id: setdirs
        run: echo "dir=$(ls -d modules/* | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  validate:
    name: "TF Check"
    runs-on: ubuntu-latest
    needs: [directories]
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.directories.outputs.dir) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get git status
      run: git status
    
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.7"

    - name: Terraform init
      run: terraform -chdir=${{ matrix.directory }} init

    - name: Terraform validate
      run: terraform -chdir=${{ matrix.directory }} validate

    - name: Terraform lint check
      run: terraform -chdir=${{ matrix.directory }} fmt -check

  publish:
    name: Publish
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up branch
        run: |
          git branch "release-from-${{ github.sha }}" "${{ github.sha }}"
          git checkout "release-from-${{ github.sha }}"
      - name: build changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-push: false
          skip-version-file: true
          git-branch: "release-from-${{ github.sha }}"
          create-summary: true
          skip-git-pull: true
      - name: Check a few things
        run: |
          git status
          git diff | cat
          git diff HEAD~1 | cat

