name: Publish Bundle to S3
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref to checkout and bundle'
        type: 'string'
        required: true
      bundlename:
        description: 'The suffix to append to terraform-modules-<bundlename>.tar.gz'
        type: 'string'
        required: true
  workflow_call:
    inputs:
      ref:
        description: 'The ref to checkout and bundle'
        type: 'string'
        required: true
      bundlename:
        description: 'The suffix to append to terraform-modules-<bundlename>.tar.gz'
        type: 'string'
        required: true
  pull_request:
    paths:
      - .github/workflows/publish_bundle_s3.yaml

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - id: determine-ref
        name: determine git ref
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] ; then 
            ref="${{ github.ref }}"
            tarname="terraform-modules-pr-test.tar.gz"
          else
            ref="${{ inputs.ref }}"
            tarname="terraform-modules-${{ inputs.bundlename }}.tar.gz"
          fi
          echo "ref=${ref}"
          echo "ref=${ref}" >> $GITHUB_OUTPUT
          echo "tarname=${tarname}"
          echo "tarname=${tarname}" >> $GITHUB_OUTPUT
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ steps.determine-ref.outputs.ref }}
          path: terraform-modules
      - name: Setup terraform
        # v3.1.2
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.7.5
          # https://github.com/hashicorp/setup-terraform/issues/373
          terraform_wrapper: false
      - name: Install terraform deps in folders
        run: |
          cd terraform-modules
          ./scripts/install-terraform-in-examples.sh
      - name: bundle everything
        run: |
          tar --exclude='terraform-modules/.git' -czvf "${{ steps.determine-ref.outputs.tarname }}" terraform-modules
          ls -ahl
      - name: Configure AWS credentials
        if: "${{ github.event_name != 'pull_request' }}"
        # v4.1.0
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: push to s3
        if: "${{ github.event_name != 'pull_request' }}"
        run: |
          aws s3 cp "${{ steps.determine-ref.outputs.tarname }}" s3://bigeye-bundle-distribution/terraform-modules/

