name: Lint Commits
on:
  pull_request: {}

jobs:
  test_commits:
    name: Test commit format
    runs-on: ubuntu-latest
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Setup Node
        # v4.4.0
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Check commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
