name: test and publish
permissions:
  contents: write
  issues: write
  pull-requests: write
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - modules/**/*
      - .github/workflows/test_and_publish.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  directories:
    name: List directories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.setdirs.outputs.dir }}
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: setdirs
        run: |
          # shellcheck disable=SC2012
          echo "dir=$(ls -d modules/* | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  validate:
    name: TF Check
    runs-on: ubuntu-latest
    needs: [directories]
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.directories.outputs.dir) }}
    steps:
    - name: Checkout
      # v4.2.2
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Get git status
      run: git status

    - name: Setup terraform
      # v3.1.2
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
      with:
        terraform_version: "1.5.7"

    - name: Terraform init
      run: terraform -chdir=${{ matrix.directory }} init

    - name: Terraform validate
      run: terraform -chdir=${{ matrix.directory }} validate

    - name: Terraform lint check
      run: terraform -chdir=${{ matrix.directory }} fmt -check

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - validate
    timeout-minutes: 5
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: fetch current version
        id: prevversion
        run: echo "PREVIOUS_VERSION=v$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - name: print previous version
        run: echo "${{ steps.prevversion.outputs.PREVIOUS_VERSION }}"
      - name: set up branch
        run: |
          git branch "release-from-${{ github.sha }}" "${{ github.sha }}"
          git checkout "release-from-${{ github.sha }}"
      - name: build changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@c6e8c216679c1c923820011e544cbe0e813b8057
        with:
          git-branch: "release-from-${{ github.sha }}"
          create-summary: true
          skip-git-pull: true
          release-count: 0
          input-file: CHANGELOG.md
      - name: replace tf release version in scripts
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: ./scripts/replace-terraform-version.sh "${{ steps.changelog.outputs.tag }}"
      - name: inspect git status
        run: |
          git status
          git diff | cat
          git diff HEAD~1 | cat
      # v5.2.0
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          create_branch: false
          branch: "release-from-${{ github.sha }}"
          commit_message: "chore(release): update example docs to use new version ${{ steps.changelog.outputs.tag }}"
          file_pattern: examples/**/*
          skip_fetch: true
      - name: create PR with release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        id: create-pr
        run: gh pr create --base main --head release-from-${{ github.sha }} --title "Add release notes for ${{ steps.changelog.outputs.tag }}" --body "Created by action ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: approve pr
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          gh pr review "release-from-${{ github.sha }}" --approve
        env:
          GH_TOKEN: ${{ secrets.BIGEYE_SRE_BOT_GH_PAT }}
      - name: merge PR with release info
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        id: merge-pr
        run: |
          gh pr merge "release-from-${{ github.sha }}" --admin --merge --delete-branch --subject "chore: merge release docs for ${{ steps.changelog.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release with last commit
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        # v1.16.0
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      - name: notify SDP
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          gh workflow run "TF Bump Module Version" -R "bigeyedata/semantic-data-platform" --field "previousVersion=${{ steps.prevversion.outputs.PREVIOUS_VERSION }}" --field "version=${{ steps.changelog.outputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.BIGEYE_SRE_BOT_GH_PAT }}
      - name: failure - delete branch and tag
        if: ${{ failure() && steps.changelog.outputs.skipped == 'false' }}
        run: |
          git push -d origin release-from-${{ github.sha }} || echo "failed to delete branch"
          git push -d origin ${{ steps.changelog.outputs.tag }} || echo "failed to delete tag"

  notify-on-success:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - publish
    steps:
      - name: notify slack
        if: ${{ needs.publish.outputs.skipped == 'false' }}
        # v2.0.0
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        with:
          method: chat.postMessage
          token:  ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          payload-templated: true
          payload: |
            channel: ${{ secrets.SRE_SLACK_CHANNEL_ID }}
            text: ":shipitparrot: terraform-modules successfully published version ${{ needs.publish.outputs.tag }}. [<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.publish.outputs.tag }}|Release>]" 

  notify-on-fail:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - publish
    if: |
      always() && needs.publish.result != 'success' && needs.publish.result != 'skipped'
    steps:
      - name: Notify on fail
        # v2.0.0
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        with:
          method: chat.postMessage
          token:  ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          payload-templated: true
          payload: |
            channel: ${{ secrets.SRE_SLACK_CHANNEL_ID }}            
            text: ":sadparrot: terraform-modules publish version ${{ needs.publish.outputs.tag }} failed. [<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}| GH Action>]"
