name: Lint Commits
on:
  pull_request: {}

jobs:
  test_commits:
    name: Test commit format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Check commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
