name: Validate GH Actions Workflows

on:
  pull_request:
    paths:
      - .github/**


jobs:
  actionlint_github_actions_workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: "Actionlint GH Actions workflows"
        # v1.65.2
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281
        with:
          filter_mode: file
          actionlint_flags: "--ignore SC2086 --ignore SC2046"


