name: Validate shell scripts with shellcheck

on:
  pull_request:
    paths:
      - "**/*.sh"
      - scripts/**
      - .github/workflows/validate_shell_script_syntax.yaml

jobs:
  provide_file_list:
    name: "Get list of changed files"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: "Get changed files"
        id: changed-files
        uses: tj-actions/changed-files@v42.0.2
        with:
          files: |
            **/*.sh

      - name: "Convert changed files output to list"
        id: convert_to_json_list
        # This ugly pipe through JQ is to turn the string/space separated list of strings into a json list of strings
        run: echo "matrix=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -R  -c -j 'split(" ")')" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.convert_to_json_list.outputs.matrix }}

  shellcheck:
    needs: provide_file_list
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: "Run shellcheck on scripts"
    strategy:
      fail-fast: false
      matrix:
        filename: ${{ fromJson(needs.provide_file_list.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Differential ShellCheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          # https://github.com/koalaman/shellcheck#how-to-use
          # add more files as a space separated value below.  Wildcards are okay
          cli-args: ${{ matrix.filename }}
